### ISSUE TITLE
Poor translation

### ISSUE THREAD

**Issue by AterCZE** [MicrosoftDocs/SCCMDocs.cs-cz#4]
Hello, I'd suggest showing the translated version of the article just after it has been reviewed. Right now the text in Czech makes little sense. 

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 0cf94da2-1651-3ade-8cd9-dd1917100656
* Version Independent ID: c8461e22-8c59-b8dd-6061-a06ebaefbab0
* Content: [Jaká větev použít - Configuration Manager](https://docs.microsoft.com/cs-cz/sccm/core/understand/which-branch-should-i-use#feedback)
* Content Source: [sccm/core/understand/which-branch-should-i-use.md](https://github.com/Microsoft/SCCMDocs.cs-cz/blob/live/sccm/core/understand/which-branch-should-i-use.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by AterCZE** [comment]
I know about the option to switch to English, my suggestion is to let English be the default before the translation gets reviewed.

**Comment by lichasu** [comment]
Hello, @AterCZE 

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.

Kind regards,
Microsoft DOCS International Team
